version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yonseireact_lab
    image: diorcokorea/yonseireact_lab
    volumes:
      - ./src:/app/src
    ports:
      - "88:80"
