version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yonseireact
    image: diorcokorea/yonseireact
    volumes:
      - ./src:/app/src
    ports:
      - "88:80"
