const globalVar = {
  scale: 0,
  scaleorigin: 0,
  showSpin: false,
  imgname: null,
  originimg: null,
  thumbimg: null,
  thumborigin: null,
  thumbpdf: null,
  originurl: null,
  position: null,
  keepposition: null,
  draggable: true,
  readtype: "",
  sidetype: "noimg", //nude, added
  fillcolor: null,
  drawtype: [true, true, true],
  drawpdf: [true, true, true],
  counting: null,
  triggerthumb: false,
  triggerpdf: false,
  triggerreset: false,
  contextinfo: null,
  transforminit: null,
  openPopup: false,
  spinshow: false,
  togglers: {},
};

export { globalVar };
